spring:
  datasource:
    url: jdbc:postgresql://dpg-cttv90lumphs73ej0l10-a.oregon-postgres.render.com:5432/db_spring_boot
    username: alexander
    password: EwjwWYpxpJwRGZYlUhozix0FUxTJe6mT
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update # O puedes usar 'none' si prefieres que no se generen cambios automáticos en las tablas
    show-sql: true # Para mostrar las consultas SQL en los logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Para un formato más legible de las consultas SQL en los logs
